### ISSUE TITLE
Trimester 3 Week 3 Review Ticket

### ISSUE THREAD

**Issue by Leonard514** [Leonard514/FastPage#14]
Here are some stuffs:

- [x] MCQ Reflection is [here](https://leonard514.github.io/FastPage/notes/MCQ5reflection). Intentionally brief so that others can take the test by themselves.
- [x] Parallel Computing and Hashmap notes + hack are [here](https://leonard514.github.io/FastPage/notes/parallel). I'll be blunt and say there's barely anything for hashmaps. That's a priorities/time management issue (see below where I sunk a lot of my time)
- [x] Planning for SASS: I [took notes](https://docs.google.com/document/d/1oadZSKXNn9uzvfnVbQdJovHPRp0g_t7JwOYskNiVlW8/edit?usp=sharing) on the documentation for a solid portion of the weekend. My plan is to finish taking notes on the documentation so that with more knowledge of SASS, I will be better-equipped to make and teach the lesson.
- [x] My friend Lily has made an [outline](https://github.com/lwu1822/APCSP/commit/7e6883674beafc4fa8b3b2ff9d8acda600a8db32) using my notes. She's also got the [pull request](https://github.com/nighthawkcoders/APCSP/pull/141/commits/7e6883674beafc4fa8b3b2ff9d8acda600a8db32) up with all the front matter.

**Comment by lwu1822** [comment]
MCQ Test #4: 0.6
Hashmap and parallel computing work: Unsure
Project work: 0.6 (Took a lot of notes, very comprehensive and will help towards making quiz questions)
Outline of Lesson Plan with Pull Request on APCSP: .45
Date of Lesson on Lesson Plan Meta Data and scheduled with Teacher: .45
