### ISSUE TITLE
May Week 1 Review Ticket

### ISSUE THREAD

**Issue by Leonard514** [Leonard514/FastPage#16]
- [x] [2020 MCQ Reflection](https://leonard514.github.io/FastPage/notes/MCQ2020reflection)
- [ ] [Internet Hacks (incomplete)](https://leonard514.github.io/FastPage/2023/04/05/Topic4.html)

**Comment by Orlando-c** [comment]
Do your grading here
https://docs.google.com/spreadsheets/d/1o5Ok0Q2OouH4Tuk2TzMpdub772Jg5vNrqOpwKZXo-WQ/edit?usp=sharing
